memedata_api:
    #build: .
    image: memedata
    ports:
        - "5000:5000"
    #edit these paths to map to your local volumes
    volumes:
        - /home/erik/rand/db_dev:/tmp
        - /home/erik/rand/db:/db
    command: /app/run.py server --env production
